[workspace]
git_release_enable = false
changelog_update = false

[[package]]
name = "metrique"
changelog_include = [
    "metrique-core",
    "metrique-macro",
    "metrique-metricsrs",
    "metrique-service-metrics",
    "metrique-timesource",
    "metrique-writer",
    "metrique-writer-core",
    "metrique-writer-format-emf",
    "metrique-writer-macro",
    "metrique-aggregation"
]
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_release_enable = true
